image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main